### ISSUE TITLE
What exactly is the license (and limitations of use) for this?

### ISSUE THREAD

**Issue by ItsEddie** [sqrMin1/MonoGame.Forms#1]
Hey there!

This is fabulous. I was hoping to add this to my a Winforms UI kit I'm creating as an additional control since I myself also work in Monogame - is this allowed? I'd be happy when my UI kit is released to write a tile-editor sample with your Monogame control as a form of level editor.

Here's a quick (outdated) image of the progress I've made so far. 

![cap 2](https://user-images.githubusercontent.com/20602971/32993045-eadacd9a-cd52-11e7-8b2d-0819923fbe06.PNG)

**Edit:** I see you've got the MIT license set. Are you okay with backlinks to this github page from within the source files?

Regards, 
 - Eddie

**Comment by sqrMin1** [comment]
Yes, you can do this.

You only need to include the text from the license file to your project. You could create a text file and then copy/paste the license text to it.

Cheers.
