### ISSUE TITLE
60 fps

### ISSUE THREAD

**Issue by lofcz** [sqrMin1/MonoGame.Forms#12]
Running one instance of `UpdateWindow` control on double buffered winform on mid-tier laptop (i7 8th gen, 16gb ram). Following code executes barely 10 times a second:

`        protected override void Update(GameTime gt)
        {
            Debug.WriteLine(DateTime.Now);
        }`

Native MonoGame openGL game hits 60 cap without any problems. Is there any way to increase performance? Running project is allocating like 50 Mb of RAM only. 
Thanks in advance.

**Comment by sqrMin1** [comment]
Please turn off double buffering on the Forms containing an UpdateWindow control. The DirectX version of MonoGame.Forms renders differently than the OpenGL version in the moment.

**Comment by lofcz** [comment]
I'm using OpenGL version.

**Comment by sqrMin1** [comment]
In either way you should turn off DoubleBuffering. You don't need it in MonoGame.Forms and it will cause flickering.

The DirectX library is deffinitley way faster in the moment. If you need a very good performance you should go with DirectX.

You could also improve performance on an OpenGL control by raising the DrawIntervall on a custom control via the PropertyWindow during design time.

**Comment by lofcz** [comment]
Thanks for your replies. I'd herebly suggest to add this note about DX/GL somewhere in the readme.md file. Cheers!

**Comment by sqrMin1** [comment]
No problem.

There is already a note in the Readme.md file regarding the DrawIntervall. It sais:

> Note: To raise the performance of an OpenGL UpdateWindow, it's recommended to change the DrawIntervall from 1ms to 50ms or 100ms!

But I will later add a note regarding DoubleBuffering too.

Thanks for reporting!

**Comment by lofcz** [comment]
I mean, I've read this note but at least for me it doesn't make clean that GL performance will be worse than DX, that should be, imho, noted.

**Comment by lofcz** [comment]
Edit2: After switching to DX I'm getting smooth 60 fps.

**Comment by sqrMin1** [comment]
Added **Tips & Tricks / Dos & Don'ts** section to the **Readme.md** file under the **Building** topic.
