### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by lofcz** [sqrMin1/MonoGame.Forms#15]
Is there currently support for playing videos in DX version? Tried same code to get a video running under Forms.DX and native MonoGame 3.8 latest dev build. Works fine on native MG, fails with nullexceptionerror in Forms, while loaded video contains correct values for properties like duration, fps, location. 

            private VideoPlayer vp = null;
            Video vid = Content.Load<Video>("MyVideo");

            vp = new VideoPlayer();
            vp.Play(vid);

**Comment by sqrMin1** [comment]
Fixed in e9c99f514bd7ddf34f06b77e803a048f4deea367

**Comment by lofcz** [comment]
For me it now crashes on _session being null. Using MonoGame 3.8.0.271. Any idea what could go wrong? _session is not initialized for some reason. 

[![Bezejmenn.png](https://i.postimg.cc/ZYsrsdBh/Bezejmenn.png)](https://postimg.cc/yW9gkWyf)

**Comment by sqrMin1** [comment]
You need to take the MonoGame.Framework which comes together with the NuGet package (3.8.0.270).

I tried the new MonoGame.Forms.DX (2.3.0) on a fresh WindowsForms project and the VideoPlayer works there.

Please verify that by creating a fresh new WindowsForms project and install the MonoGame.Forms.DX nuget there. Try to load a video and see if it works.

It could also help to do a clean rebuild of your solution.

**Comment by lofcz** [comment]
Edit: tried your minimal example and it works fine, error must be on my side. Sorry for bothering you with this,
