### ISSUE TITLE
Eto.Forms

### ISSUE THREAD

**Issue by Shadowblitz16** [sqrMin1/MonoGame.Forms#16]
does this work with eto.forms?
if not can support be added for it?

eto.forms is a cross platform gui library that the monogame pipeline is made from. 
https://github.com/picoe/Eto

**Comment by sqrMin1** [comment]
Thanks for the request, but i'm currently not having the time to take a look into Eto.Forms support.

However there is already a GTK repo available:
https://github.com/SpiceyWolf/MonoGame.Framework.Gtk

It's also possible to run a MonoGame.Forms.GL project with mono:
http://mark-dot-net.blogspot.com/2014/06/running-windows-forms-on-linux-with-mono.html

I would also accept pull requests if someone wants to do the Eto.Forms support.
