### ISSUE TITLE
Mac / LinuX support (Mono WinForms)? Alternatives?

### ISSUE THREAD

**Issue by therhinodude** [sqrMin1/MonoGame.Forms#18]
I'm assuming that the way this is implemented it's just not possible to ever have multiplatform support built upon Mono's WinForms implementation?

I'm doing research for editor of upcoming project, and would prefer to target all 3 desktop OS, not just Windows.

If not, the other obvious alternative is trying to build the entire GUI in the game itself, which is going to be a  nightmare.

Any other thoughts on how to provide a rich cross-platform desktop editor for a monogame title the embeds the actual game rendering logic?  Something for QT, GTK, etc?

**Comment by sqrMin1** [comment]
Mono info:
You can compile your editor project with mono.

Gtk info:
https://github.com/SpiceyWolf/MonoGame.Framework.Gtk
https://github.com/cra0zy/MonoGame/tree/gtk

It's also possible to use [ImGui.Net](https://github.com/mellinoe/ImGui.NET) together with the MonoGame.Framework.
