### ISSUE TITLE
Controls in two different forms | OpenGL

### ISSUE THREAD

**Issue by Kanewersa** [sqrMin1/MonoGame.Forms#19]
How does one render a Control in another (newly created) form?
Whenever I try to draw a Control inside a second form all the Controls get messed up and turn black after Invalidation. I've been trying to fix it for some time, messing around with Swap Chain Render Target, but with no result.
That problem doesn't persist when using DX library.

![first](https://user-images.githubusercontent.com/30356293/62431173-4329da00-b725-11e9-9501-51bca41d8e9a.png)
![second](https://user-images.githubusercontent.com/30356293/62431176-4de46f00-b725-11e9-9328-cee0d3e73a54.png)

**Comment by sqrMin1** [comment]
I wouldn't recommend instatiating a new Form and programmatically creating a MonoGameControl as a child inside this new Form. It may work or not for the end user. 

A better approach would be using something like [DockPanelSuit](https://github.com/dockpanelsuite/dockpanelsuite) for dockable and floating Forms. 

I use this for myself together with MonoGame.Forms projects and I made sure, that the DockPanelSuit works flawlessy with this library.
