### ISSUE TITLE
Resizable control?

### ISSUE THREAD

**Issue by Thraka** [sqrMin1/MonoGame.Forms#2]
Do you have an example on having a resizable form that when the draw/update control is resized, the backbuffer is resized too? Currently it looks like the viewport is resized to fit the control, which makes everything squished or zoomed.

**Comment by sqrMin1** [comment]
I just pushed a new version with the desired feature. Please check it out:

Release: https://github.com/sqrMin1/MonoGame.Forms/releases/tag/1.6.0
NuGet: https://www.nuget.org/packages/MonoGame.Forms/1.6.0

**Comment by Thraka** [comment]
Awesome, I'll check this out! Do you happen to know what events fire that would tell me that it's been resized?

**Comment by sqrMin1** [comment]
Yes, the **GraphicsDeviceControl** just inherits from a regular **System.Windows.Forms.Control**, so it's possible to use the events you are used to know from a classical windows forms app.

For example: **OnResize** and **OnClientSizeChanged**.

You can use it simply by overriding this events in you custom control like this:

```
protected override void OnClientSizeChanged(EventArgs e)
{
       base.OnClientSizeChanged(e);
}
```

**Comment by Thraka** [comment]
Oh duh! Thanks!

**Comment by Thraka** [comment]
The `GraphicsDevice.PresentationParameters` do not seem to be changing to match the render area. Shouldn't this change?

**Comment by sqrMin1** [comment]
43465d3f27c170b37fa7a6c40d88b1f68af486c8 should fix this issue. Thanks for pointing this out.

**Comment by Thraka** [comment]
Working thanks!
