### ISSUE TITLE
Fixed Time Step

### ISSUE THREAD

**Issue by venedele** [sqrMin1/MonoGame.Forms#23]
As far as I was able to investigate there was no proper IsConstantTimeStep Property anywhere at the moment or at least not a conventional one. The DrawInterval Property alone is a possible alternative but I experienced a lot of inconsistencies in the framerate when i try to use it.

P.S My problem with DrawInterval might be caused by VerticalSync, but I also could not find the SynchronizeWithVerticalRetrace Property.

**Comment by sqrMin1** [comment]
I assume you are using the GL version, right?

The GL implementation is not perfectly done and the DrawInterval is just there to have some rough control over the frames.

It's best to have just a small render window with the GL version in the moment.
