### ISSUE TITLE
NullRef Exception in Draw() of MonoGameControl caused by form's WindowState.Maximized

### ISSUE THREAD

**Issue by energyuser** [sqrMin1/MonoGame.Forms#24]
Hello, I have a custom control inheriting from `MonoGameControl` (just like the tutorial). I override the methods and have this code in `Draw`:

```
protected override void Draw()
{
    base.Draw();

    Editor.spriteBatch.Begin(); // <--- NullReferenceException: Editor is null
    ControlContainer.Draw(Editor.spriteBatch);
    Editor.spriteBatch.End();
}
```

I tried debugging and I found the culprit is here:

```
protected override void Initialize()
{
    base.Initialize(); // <-- After this line it jumps directly to Draw(), and Editor is still null
    // All the code here is ignored
}
```

I'm using a WinForms project and the latest version of MonoGame.Forms.DX from nuget.

**Comment by energyuser** [comment]
I made a new and clean winforms project, installed from nuget and found the cause of the problem:
Both this problem and https://github.com/sqrMin1/MonoGame.Forms/issues/21 were caused because I migrated my `packages.config` to `PackageReference`. If I don't update it works. Is there any way you can fix that @sqrMin1 ? I will return to packages.config as a workaround.

**Comment by energyuser** [comment]
Update: Setting `Form.WindowState` to `WindowState.Maximized` causes the null reference exception. However, the PackageReference migration causes issue #21.

**Comment by sqrMin1** [comment]
I tried maximizing the window and I didn't receive a NullReferenceException.

I'm not sure how I could help you with this.

**Comment by energyuser** [comment]
I can give you a minimal test project that is guaranteed to fail. Did you convert `packages.config` -> `PackageReference`?

**Comment by joshrickard** [comment]
I ran into the same issue although it didn't seem specific to the maximize state of the form. Checking for null seemed to be a workaround for me:

```
    protected override void Draw()
    {
      base.Draw();
      if (Editor == null) return;

      Editor.spriteBatch.Begin();
      
      Editor.spriteBatch.DrawString(Editor.Font, "Hello World", new Vector2(
        (Editor.graphics.Viewport.Width / 2) - (Editor.Font.MeasureString("Hello World").X / 2),
        (Editor.graphics.Viewport.Height / 2) - (Editor.FontHeight / 2)),
        Color.White
      );

      Editor.spriteBatch.End();
    }
```

**Comment by sqrMin1** [comment]
I added additional NullReferenceException checks with 2ee8f84ff10a71dd212c39f1cf63beb428a2a793
It's on the master. 

Can someone check if this solves the problem?

Are you using Visual Studio 2019?

**Comment by joshrickard** [comment]
I am using Visual Studio 2019.

**Comment by energyuser** [comment]
Testing, will edit when I have results.

**Comment by sqrMin1** [comment]
@energyuser @joshrickard 

You need to give MonoGame.Forms more time on initialization. I recommend changing the window state of a form containing a MonoGameControl in the Load event of a form.

Like so:

```c#
private void Form1_Load(object sender, EventArgs e)
{
    WindowState = FormWindowState.Maximized;
}
```

This works for me.
