### ISSUE TITLE
can monogame forms support the soundeffect？

### ISSUE THREAD

**Issue by hejoy91** [sqrMin1/MonoGame.Forms#25]
can monogame forms support the soundeffect？
i load the wav xnb file，but it doesn't work，no sound play。
but i use it in a xna framework project，it can play sound well，with the same code。。

**Comment by hejoy91** [comment]
and your Demo without anything with audio，please tell me how i can solve it。

**Comment by hejoy91** [comment]
![VAT{ 5YX)3FFXW@N`KTBT)Q](https://user-images.githubusercontent.com/24309797/74396290-7ffd2900-4e4c-11ea-9395-ce7f89e833b9.png)
i use the same wav file in a xna gamestudio 4.0 ，everything goes well，please tell me what others i can do。 @sqrMin1 sqrMin1

**Comment by sqrMin1** [comment]
Yes, SoundEffect is supported in MonoGame.Forms.

Try playing the sound in `Update()`
