### ISSUE TITLE
Mouse status getting

### ISSUE THREAD

**Issue by Rombersoft** [sqrMin1/MonoGame.Forms#27]
Hello Friend! Do you use native GTK# events or native SDL methods for getting mouse state?
What is monogame version did you apply?

**Comment by sqrMin1** [comment]
For the GL version I use SDL Events, but you don't need to care. Just use the mouse state from the MonoGame.Framework.

Regarding MonoGame versions you can find information in the Readme.md file right at the top.

**Comment by Rombersoft** [comment]
I work with some touchscreen on Linux, which works on winforms but does not work with Monogame.. There are Zytronic, SONiX, and multi touch noname
