### ISSUE TITLE
Not suitable for 3D renders

### ISSUE THREAD

**Issue by Soraiko** [sqrMin1/MonoGame.Forms#28]
What is the DrawInterval property for the MonoGameControl ?!
I hope you're not using a System.Windows.Forms.Timer ?
My 3D renders very slow with this control, and I ported my whole MonoGame to your MonoGame.Forms because I needed a form with OpenGL, to enable antialiasing.
Official DirectX MonoGame already allows to catch the GameWindow as a System.Windows.Forms.Form, and allows to append System.Windows.Forms.Controls already.
This is impossible with OpenGL MonoGame though.
You could have specified that your solution renders too slow for 3D projects like mine.
It is not my project being wrong, because I tried to render an empty game in 1600x900 and the FPS drops to 5. Not good !

**Comment by sqrMin1** [comment]
The OpenGL implementation is not made with performance in mind. You need to use the windows version if you want full performance.

This is also cleary stated in the Readme.md file.
