### ISSUE TITLE
Referencing GraphicsDevice causes a NullReferenceException

### ISSUE THREAD

**Issue by CatoNator** [sqrMin1/MonoGame.Forms#29]
As of version 2.3.9, evoking GraphicsDevice (MonoGame.Forms.Controls.get_GraphicsDevice) causes a nullreferenceexception. Happens in both GL and DX builds, doesn't seem to be a way around it.

**Comment by sqrMin1** [comment]
Are you using visual studio 2019?

**Comment by CatoNator** [comment]
Yes I am.

I managed to solve the issue already, but here's what I tried to do:

I tried to render each node from a TreeView by calling the drawing function from inside the node itself. Apparently this causes just about every variable to be nullified, not just GraphicsDevice specifically returning null.

Traversing through the tree from inside the preview window works fine.
