### ISSUE TITLE
Getting a null reference exception (Editor.get returned null) when trying to invoke "Editor.spriteBatch.Draw(...)"

### ISSUE THREAD

**Issue by jtcuth48** [sqrMin1/MonoGame.Forms#31]

**Comment by sqrMin1** [comment]
Are you trying to set the corresponding form to fullscreen before invoking Editor.spriteBatch.Draw()?

Is this a fresh MonoGame.Forms project?

I need more information.

**Comment by jtcuth48** [comment]
Oh man. It was because I was setting the form to fullscreen.

Thank you so much! Feel free to close

**Comment by sqrMin1** [comment]
No problem, glad I could help.

If you want to maximize a window then do it in the form load event like so:

```c#
private void Form1_Load(object sender, EventArgs e)
{
    WindowState = FormWindowState.Maximized;
}
```

This will work.
