### ISSUE TITLE
How do I create a spritefont?

### ISSUE THREAD

**Issue by jasons-codes** [sqrMin1/MonoGame.Forms#32]
How to create spritefont in MonoGame is explained, but I am not sure how to create spritefont in MonoGame.Forms.

However, the current version of MonoGame is .NET Standard 2.0, so the installation was skipped.
I am only using MonoGame.Forms and I would like to know how to create spritefont at this time.

My purpose is to adjust the font size, and I only need to support basic English ASCII for arial, which is the default font of Windows operating system.

I also tried printing the built-in Editor.font by scaling, but the output was not good.

**Comment by sqrMin1** [comment]
It works the same as in MonoGame. You need to have the spritefont compiled to the xnb format. After that you can load it like any other content file with the content manager.

**Comment by jasons-codes** [comment]
Thanks to it I applied it correctly.
Thanks for the answer!
