### ISSUE TITLE
Problems with WindowsFormHost on WPF

### ISSUE THREAD

**Issue by Thraka** [sqrMin1/MonoGame.Forms#4]
Just wanted to test using this in WPF (the existing WPF MonoGame control someone else makes has a lot of weird issues).

1. The Draw method is called only one time. 
2. The Update method is never called.

**Comment by sqrMin1** [comment]
This is not an issue, because MonoGame.Forms is (like the name implies) designed to be used in a Windows Forms environment **_only_**.

If you need WPF support please search for "MonoGame WPF Interop".
