### ISSUE TITLE
Fail to load Texture2D of png file that's 2560x2560 of size

### ISSUE THREAD

**Issue by Cookiesliyr** [sqrMin1/MonoGame.Forms#49]
Good day, first i would like to thank you a lot for this project, i have a huge game editor tool for my engine that taking care of the data side of everything, and i am happy with it except its made on C# Mapforms which means it uses GDI+, i didn't wana switch to WPF or C++ just because of that issue till i found your tool.

the game engine and game projects are made on Monogame and they can load the images but using the piepline after compiling them to .xnb, not sure if i can do it in Monogame.Forms in this version.

Anyhow, i successfully added the control and i loaded sample of images and the tiles and it worked, but when i start loading the other textures using Texture2D.FromStream() it kept failing on some images, when i change the format nothing happen, but i discovered if i change their size they work if they are small. i have many images of size 1600x1600 and 2560x2560 and the 1600 works fine but the 2560 fails and break the loop to load all the images, i tried to find other ways to load images but to be honest i have been working for long today and things were running fine and smoth till this issue came up and i am a bit too tired <_<;

This is the error i get
Attempt to create a TextureException thrown: 'System.InvalidOperationException' in MonoGame.Framework.dll

unfortuntally i don't think i can debug and troubleshoot the dll file while it is compiled, not sure if there is a way, it doesn't tell me what the issue but i found it was defintally the size.

sorry for failing writting smaller messages, do you know how to tackle this issue? is there a way to pipeline the texture in .xnb or something or load them in different way? should i try older MonoGame.Forms when it support the pipeline, the Tool is completly seperated from the engine, all what i want from it is the 2d Accelration to preview the map and run only on Windows 10, nothing else, i don't need any fancy other things from monogame.

Note: i tried to replace the MonoGame.Framework.dll manually just to see if it will pass, but that crashed the whole APP XD guess i gutted a lot of code to make it work like this.

**Comment by BlizzCrafter** [comment]
Hello @Cookiesliyr!

Yes, you can load your images with the pipeline from MonoGame. This is what the sample project of MonoGame.Forms is doing. You can do it the same like this: `Editor.Content.Load<Texture2D>("Your Image")`

Just remember to set the GraphicsProfile to "HiDef" in your control properties if you want to load very large images:

![graphicsprofile](https://github.com/user-attachments/assets/0e397a69-9f4f-439a-b1e8-7c0d0fe0754b)

**Comment by Cookiesliyr** [comment]
To be honest i found you tool like 2 days ago and i should spend much more time on it to understand how did you pipeline your images, i don't wana do any manual work like dragging the xnb file into the project.

The good news is when i checked the control that i draw the map on and changed the GraphicsProfile to HiDef as you suggested it accepted all images from the stream! except the Effect one cause i guess it is too big, they are only used in the engine so when i wrote a condtion to ignore them all images got loaded! 
![image](https://github.com/user-attachments/assets/3e28cce9-2c57-46f7-9405-f6efb606153e)

for now i will try to make the map editor functional before i try to make it fancy and pipeline the images to XNB and such, thank you very much for the help and all your hard work to make this possible! i have been trying to find an easy to have 2d accelarator for my map editor without the need to use a different langauge for a few years, and it seems this is finally possible thanks to you!
