### ISSUE TITLE
Does this work on VS 2017 and MonoGame 3.6?

### ISSUE THREAD

**Issue by Shadowblitz16** [sqrMin1/MonoGame.Forms#5]
hello I am having trouble getting this to work on VS 2017 and MonoGame 3.6.
when I try to install it from the nuget package manager it gives me this..

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'MonoGame.Forms 1.6.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by sqrMin1** [comment]
You need to change the NetFramework version to 4.5.1.

**Comment by Shadowblitz16** [comment]
ok thankyou

**Comment by Thraka** [comment]
I could not get it working with .NET 4.5.1 and the MonoGame 3.6 NuGet package.

```error
**System.IO.FileLoadException: 'Could not load file or assembly 'SharpDX.DXGI, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
**
```

The version of SharpDX.DXGI that is shipped with MonoGame 2.6 is 2.6.3.0

**Comment by sqrMin1** [comment]
If you want to work with MonoGame 3.6 (only WindowsDX is supported), then you need to download the source of MonoGame.Forms, exchange the MonoGame.Framworks, and rebuild the solution.

**Comment by Thraka** [comment]
Do you know offhand if there is any sort of feature you're using of the later version of MonoGame or SharpDX? Or in theory it should just all work if recompiled and linked to the older version?

**Comment by sqrMin1** [comment]
Yes, I mainly use the higher version of the MonoGame.Framework to have the native mouse input support from the framework, so that you could do `Mouse.GetState()` to get mouse input.

But you can also use the event system from WindowsForms to handle mouse input (take a look at the included samples to get a clue). 

Despite that everything should easily work with MonoGame 3.6 just by exchanging the framework and do a fresh rebuild.

**Comment by Shadowblitz16** [comment]
@sqrMin1  I'm not sure what you mean by exchange the MonoGame.FrameWorks. care to explain?
however it seems to run fine in a winforms project I haven't tested it with the MonoGame project yet.

**Comment by sqrMin1** [comment]
@Shadowblitz16 I just meant remove the reference from the new MonoGame.Framework and add a reference to the MonoGame.Framework 3.6.

BTW: MonoGame.Forms is just for having a render window inside a WindowsForms project. It's not designed to be used it in a MonoGame project.

**Comment by Shadowblitz16** [comment]
@sqrMin1  thankyou I will try it.
Also I mean't I have't tried drawing to the monogame.form widget yet from monogame.

**Comment by Stephanowicz** [comment]
I've the same error like @Thraka

**Comment by sqrMin1** [comment]
@Stephanowicz 

Thanks for reporting this issue. It should be fixed with the newest [NuGet Package](https://www.nuget.org/packages/MonoGame.Forms/1.6.6.1).
